# Generated by Django 5.2.6 on 2025-12-18 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de l'invité"),
                ),
                (
                    "wedding_text",
                    models.CharField(
                        default="Nous avons le plaisir de vous inviter à notre mariage",
                        max_length=500,
                        verbose_name="Texte d'invitation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vip", "VIP"),
                            ("standard", "Standard"),
                            ("famille", "Famille"),
                            ("amis", "Amis"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "statut_guest",
                    models.CharField(
                        choices=[
                            ("COUPLE", "Couple"),
                            ("SINGLE", "Célibataire"),
                            ("FAMILY", "Famille"),
                        ],
                        default="COUPLE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "scanned",
                    models.BooleanField(default=False, verbose_name="QR Code scanné"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date du scan"
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Code QR unique",
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="Image QR Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invité",
                "verbose_name_plural": "Invités",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nom/Numéro de la table",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description de la table"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WeddingConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_capacity", models.IntegerField(default=370)),
                ("current_occupancy", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date et heure du scan"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=True, verbose_name="Scan réussi"),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_history",
                        to="invitations.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de scan",
                "verbose_name_plural": "Logs de scan",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.AddField(
            model_name="guest",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guests",
                to="invitations.table",
                verbose_name="Table assignée",
            ),
        ),
    ]
