# Generated by Django 5.2.6 on 2025-12-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="capacity",
            field=models.IntegerField(default=4, verbose_name="Capacité de la table"),
        ),
        migrations.AlterField(
            model_name="guest",
            name="status",
            field=models.CharField(
                choices=[
                    ("VIP", "vip"),
                    ("STANDARD", "Standard"),
                    ("FAMILLE", "Famille"),
                    ("AMIS", "Amis"),
                ],
                default="standard",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
