# Generated by Django 5.2.6 on 2025-12-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0002_table_capacity_alter_guest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de suppression"
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
    ]
