# Generated by Django 5.2.6 on 2025-12-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0003_table_deleted_at_table_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="name",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="status",
        ),
        migrations.AddField(
            model_name="table",
            name="category",
            field=models.CharField(
                choices=[
                    ("VIP", "VIP"),
                    ("STAND", "Standard"),
                    ("FAM", "Famille"),
                    ("AMI", "Amis"),
                    ("AUTRE", "Autre"),
                ],
                default="STAND",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="capacity",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="table",
            name="description",
            field=models.TextField(blank=True, default="Aucune description", null=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
