# Generated by Django 5.2.6 on 2025-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invitations",
            "0004_remove_guest_name_remove_guest_status_table_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="name",
            field=models.CharField(
                blank=True,
                default="Nom de l'invité",
                max_length=200,
                null=True,
                verbose_name="Nom de l'invité",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="status",
            field=models.CharField(
                choices=[
                    ("VIP", "VIP"),
                    ("STAND", "Standard"),
                    ("FAM", "Famille"),
                    ("AMI", "Amis"),
                    ("AUTRE", "Autre"),
                ],
                default="STAND",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
