# Generated by Django 5.2.6 on 2025-12-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0005_guest_name_guest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="wedding_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte de mariage"
            ),
        ),
    ]
