# Generated by Django 5.2.4 on 2025-12-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0006_alter_guest_wedding_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="weddingconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
